// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}{
	Version:     "2.0.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "星云盘 V2 API",
	Description: "星云盘 V2 是一个基于 Go + GORM + Redis 的高性能云盘系统\n\n## 功能特性\n- 用户注册与登录（JWT 认证）\n- 文件上传与下载（支持秒传、分片上传）\n- 文件夹管理（创建、重命名、移动、删除）\n- 文件分享（密码保护、过期时间）- Phase 5\n- 文件搜索（多条件过滤）- Phase 5\n- 回收站（软删除、恢复）- Phase 5\n- 版本管理（历史版本、恢复）- Phase 5\n- 协作功能（权限管理）- Phase 5\n\n## 认证方式\n大部分 API 需要在请求头中携带 JWT Token：\n```\nAuthorization: Bearer <access_token>\n```",
}

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfoInstance = swaggerInfo{
	Version:     "2.0.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "星云盘 V2 API",
	Description: "星云盘 V2 API 文档",
}

func init() {
	// This function is intentionally left empty
	// Swagger documentation will be generated by swag init command
}
