import type { OAuthApp, OAuthPermission } from './types';

export const scopeOptions = ['profile', 'email', 'openid', 'files.read', 'files.write', 'shares.manage', 'offline_access'];

const createPermissions = (enabledIds: string[], writeIds: string[] = []): OAuthPermission[] => {
  const enabled = new Set(enabledIds);
  const writes = new Set(writeIds);
  return [
    {
      id: 'openid',
      title: 'openid (OIDC)',
      description: '用于 OpenID Connect 身份识别。',
      scope: 'openid',
      enabled: true,
      required: true,
      icon: 'document',
    },
    {
      id: 'email',
      title: 'email (OIDC)',
      description: '读取用户邮箱地址和邮箱验证状态。',
      scope: 'email',
      enabled: enabled.has('email'),
      icon: 'document',
    },
    {
      id: 'profile',
      title: 'profile (OIDC)',
      description: '读取用户昵称、头像和基础资料。',
      scope: 'profile',
      enabled: enabled.has('profile'),
      icon: 'document',
    },
    {
      id: 'offline_access',
      title: '离线访问',
      description: '在用户未主动使用应用时保持访问权限。',
      scope: 'offline_access',
      enabled: enabled.has('offline_access'),
      icon: 'offline',
    },
    {
      id: 'userinfo',
      title: '个人资料',
      description: '你的账户个人资料信息，如昵称、邮箱、头像、设置等。',
      scope: writes.has('userinfo') ? 'UserInfo.Write' : 'UserInfo.Read',
      enabled: enabled.has('userinfo'),
      mode: writes.has('userinfo') ? 'write' : 'read',
      modeSwitch: true,
      icon: 'user',
    },
    {
      id: 'security',
      title: '安全信息',
      description: '账户的敏感安全信息，如通行密钥、二步验证、登录日志等。',
      scope: writes.has('security') ? 'UserSecurityInfo.Write' : 'UserSecurityInfo.Read',
      enabled: enabled.has('security'),
      mode: writes.has('security') ? 'write' : 'read',
      modeSwitch: true,
      icon: 'lock',
    },
    {
      id: 'files',
      title: '文件',
      description: '你拥有的文件和有权限访问的其他用户的文件。',
      scope: writes.has('files') ? 'Files.Write' : 'Files.Read',
      enabled: enabled.has('files'),
      mode: writes.has('files') ? 'write' : 'read',
      modeSwitch: true,
      icon: 'folder',
    },
    {
      id: 'shares',
      title: '分享链接',
      description: '文件的分享链接。',
      scope: writes.has('shares') ? 'Shares.Write' : 'Shares.Read',
      enabled: enabled.has('shares'),
      mode: writes.has('shares') ? 'write' : 'read',
      modeSwitch: true,
      icon: 'share',
    },
    {
      id: 'workflow',
      title: '后台任务',
      description: '文件处理相关的后台任务，如离线下载、文件解压缩等。',
      scope: writes.has('workflow') ? 'Workflow.Write' : 'Workflow.Read',
      enabled: enabled.has('workflow'),
      mode: writes.has('workflow') ? 'write' : 'read',
      modeSwitch: true,
      icon: 'task',
    },
    {
      id: 'finance',
      title: 'Finance.Read',
      description: '积分、兑换码、订单等。',
      scope: writes.has('finance') ? 'Finance.Write' : 'Finance.Read',
      enabled: enabled.has('finance'),
      mode: writes.has('finance') ? 'write' : 'read',
      modeSwitch: true,
      icon: 'finance',
    },
    {
      id: 'dav',
      title: 'WebDAV 账号',
      description: '你的 WebDAV 账号。',
      scope: writes.has('dav') ? 'DavAccount.Write' : 'DavAccount.Read',
      enabled: enabled.has('dav'),
      mode: writes.has('dav') ? 'write' : 'read',
      modeSwitch: true,
      icon: 'dav',
    },
    {
      id: 'admin',
      title: '管理员权限',
      description: '站点设置和全部用户的全部数据。',
      scope: 'Admin.Read',
      enabled: enabled.has('admin'),
      icon: 'admin',
    },
  ];
};

export const oauthAppsSeed: OAuthApp[] = [
  {
    id: 'ios-ipados',
    name: 'iOS/iPadOS 客户端',
    description: '星云盘移动端官方登录与文件同步入口。',
    appName: 'application:setting.iOSApp',
    iconPath: '/static/img/xingyunpan_ios.svg',
    clientId: '220db97a-44a3-44f7-99b6-d767262b4daa',
    clientSecret: '',
    redirectUris: ['/callback/ios', 'xingyunpan://oauth/callback'],
    scopes: ['profile', 'email', 'openid', 'offline_access', 'UserInfo.Write', 'UserSecurityInfo.Write', 'Files.Write', 'Shares.Write', 'Workflow.Write', 'Finance.Write', 'DavAccount.Write'],
    isSystem: true,
    enabled: true,
    createdAt: '2026-05-18 09:12',
    updatedAt: '2026-05-22 20:18',
    tokenTtl: '30 天',
    refreshTokenTtlSeconds: 7776000,
    permissions: createPermissions(
      ['email', 'profile', 'offline_access', 'userinfo', 'security', 'files', 'shares', 'workflow', 'finance', 'dav'],
      ['userinfo', 'security', 'files', 'shares', 'workflow', 'finance', 'dav'],
    ),
  },
  {
    id: 'xingyunpan-desktop',
    name: '星云盘桌面客户端',
    description: '星云盘桌面端 OAuth 授权，用于挂载、同步与外部客户端接入。',
    appName: 'application:oauth.desktop',
    iconPath: '/static/img/xingyunpan_desktop.svg',
    clientId: '393a1839-f52e-498e-9972-e77cc2241eee',
    clientSecret: '',
    redirectUris: ['/callback/desktop', 'http://127.0.0.1:5212/callback', 'xingyunpan://oauth/callback'],
    scopes: ['profile', 'email', 'openid', 'offline_access', 'UserInfo.Write', 'Workflow.Write', 'Files.Write', 'Shares.Write'],
    isSystem: true,
    enabled: true,
    createdAt: '2026-05-19 11:30',
    updatedAt: '2026-05-22 19:42',
    tokenTtl: '14 天',
    refreshTokenTtlSeconds: 7776000,
    permissions: createPermissions(
      ['email', 'profile', 'offline_access', 'userinfo', 'files', 'shares', 'workflow'],
      ['userinfo', 'files', 'shares', 'workflow'],
    ),
  },
];
